// react/src/app/app.tsx
import { IgrNavDrawer, IgrNavDrawerItem, IgrNavDrawerModule } from '@infragistics/igniteui-react';
import { Outlet, useNavigate } from 'react-router-dom';
import styles from './app.module.css';
import createClassTransformer from './style-utils';

IgrNavDrawerModule.register();

export default function App() {
  const navigate = useNavigate();
  const classes = createClassTransformer(styles);
  const uuid = () => crypto.randomUUID();

  return (
    <>
      <div className={classes("column-layout master-view-container")} key={uuid()}>
        <div className={classes("row-layout group")} key={uuid()}>
          <IgrNavDrawer open="true" position="relative" className={classes("nav-drawer")} key={uuid()}>
            <div style={{display: 'contents'}} onClick={() => navigate('/input-group')} key={uuid()}>
              <IgrNavDrawerItem key={uuid()}>
                <div slot="content" key={uuid()}>Input group</div>
              </IgrNavDrawerItem>
            </div>
            <div style={{display: 'contents'}} onClick={() => navigate('/other-inputs')} key={uuid()}>
              <IgrNavDrawerItem key={uuid()}>
                <div slot="content" key={uuid()}>Other inputs</div>
              </IgrNavDrawerItem>
            </div>
          </IgrNavDrawer>
          <div className={classes("view-container")} key={uuid()}>
            <Outlet></Outlet>
          </div>
        </div>
      </div>
    </>
  );
}

// web-components/src/app/app.ts
import { html, css, LitElement } from 'lit';
import { customElement } from 'lit/decorators.js';
import { Router } from '@vaadin/router';
import { routes } from './app-routing.js';
import { defineComponents, IgcNavDrawerComponent } from 'igniteui-webcomponents';

defineComponents(IgcNavDrawerComponent);

@customElement('app-root')
export default class App extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
    }
    .row-layout {
      display: flex;
    }
    .group {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
      min-width: 50px;
      min-height: 50px;
      flex-grow: 1;
    }
    .nav-drawer {
      min-width: min-content;
      min-height: 0;
      max-width: 320px;
      flex-shrink: 0;
    }
    .view-container {
      overflow: auto;
      display: block;
      position: relative;
      flex-grow: 1;
    }
    .nav-drawer::part(main) {
      width: 320px;
    }
  `;

  render() {
    return html`
      <link rel='stylesheet' href='../../ig-theme.css'>
      <div class="row-layout group">
        <igc-nav-drawer ?open="${true}" position="relative" class="nav-drawer">
          <igc-nav-drawer-item @click="${() => Router.go('/input-group')}">
            <div slot="content">Input group</div>
          </igc-nav-drawer-item>
          <igc-nav-drawer-item @click="${() => Router.go('/other-inputs')}">
            <div slot="content">Other inputs</div>
          </igc-nav-drawer-item>
        </igc-nav-drawer>
        <router-outlet class="view-container"></router-outlet>
      </div>
    `;
  }

  firstUpdated() {
    const outlet = this.shadowRoot?.querySelector('router-outlet');
    const router = new Router(outlet);
    router.setRoutes(routes);
  }
}
