// web-components/src/app/other-inputs/other-inputs.ts
import { html, css, LitElement } from 'lit';
import { customElement, state } from 'lit/decorators.js';
import { defineComponents, IgcCalendarComponent, IgcCheckboxComponent, IgcComboComponent, IgcRadioComponent, IgcRadioGroupComponent, IgcRangeSliderComponent, IgcRatingComponent, IgcSelectComponent, IgcSliderComponent, IgcSwitchComponent } from 'igniteui-webcomponents';
import { CategoriesType } from '../models/Northwind/categories-type';
import { northwindService } from '../services/Northwind-service';

defineComponents(IgcCheckboxComponent, IgcComboComponent, IgcRadioGroupComponent, IgcRadioComponent, IgcRatingComponent, IgcSelectComponent, IgcSliderComponent, IgcRangeSliderComponent, IgcSwitchComponent, IgcCalendarComponent);

@customElement('app-other-inputs')
export default class OtherInputs extends LitElement {
  static styles = css`
    :host {
      height: 100%;
      display: flex;
      flex-wrap: wrap;
      justify-content: space-evenly;
      align-items: flex-start;
      align-content: flex-start;
      gap: 20px;
    }
    .column-layout {
      display: flex;
      flex-direction: column;
    }
    .group {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      gap: 20px;
      position: relative;
      padding: 20px;
      min-width: 50px;
      min-height: 50px;
    }
    .row-layout {
      display: flex;
    }
    .group_1 {
      justify-content: flex-start;
      align-items: stretch;
      align-content: flex-start;
      position: relative;
    }
    .text {
      text-align: center;
      height: max-content;
      min-width: min-content;
    }
    .calendar {
      width: max-content;
      height: max-content;
      min-width: max-content;
      flex-grow: 1;
      flex-basis: 0;
    }
    .range-slider {
      width: 200px;
      height: max-content;
      min-width: 50px;
      max-width: 200px;
    }
    .user-input_2 {
      width: max-content;
      height: max-content;
    }
    .user-input {
      height: max-content;
      min-width: min-content;
    }
    .date-picker {
      height: max-content;
      min-width: 120px;
    }
    .radio {
      padding: 8px;
    }
    .slider {
      width: 200px;
      height: max-content;
      min-width: 50px;
      max-width: 200px;
    }
  `;

  constructor() {
    super();
    this.northwindCategories = northwindService.getData('CategoriesType');
  }

  @state()
  private northwindCategories: CategoriesType[] = [];

  @state()
  private value: number = 3;

  @state()
  private value1: string = '1';

  @state()
  private value2: number = 60;

  @state()
  private value3: string = '2024-04-17T00:00';

  render() {
    return html`
      <link rel='stylesheet' href='../../ig-theme.css'>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Check box
        </p>
        <igc-checkbox labelPosition="after" class="user-input_2">
          Label
        </igc-checkbox>
        <igc-checkbox labelPosition="after" class="user-input_2">
          Label
        </igc-checkbox>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Combo
        </p>
        <igc-combo ?outlined="${true}" .data="${this.northwindCategories}" label="Single select" value-key="categoryID" display-key="description" ?single-select="${true}" class="user-input"></igc-combo>
        <igc-combo ?outlined="${true}" .data="${this.northwindCategories}" label="Single select" value-key="categoryID" display-key="description" ?single-select="${true}" class="user-input"></igc-combo>
        <igc-combo ?outlined="${true}" .data="${this.northwindCategories}" label="Multi select" value-key="categoryID" display-key="description" .autoFocusSearch="${true}" ?disable-filtering="${true}" class="user-input"></igc-combo>
        <igc-combo ?outlined="${true}" .data="${this.northwindCategories}" label="Multi select" value-key="categoryID" display-key="description" .autoFocusSearch="${true}" ?disable-filtering="${true}" class="user-input"></igc-combo>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Date picker
        </p>
        <span class="date-picker">DatePicker not yet available in WebComponents</span>
        <span class="date-picker">DatePicker not yet available in WebComponents</span>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Radio group
        </p>
        <igc-radio-group alignment="horizontal" class="user-input_2">
          <igc-radio value="1" class="radio">
            Label
          </igc-radio>
          <igc-radio value="2" class="radio">
            Label
          </igc-radio>
          <igc-radio value="3" class="radio">
            Label
          </igc-radio>
        </igc-radio-group>
        <igc-radio-group alignment="horizontal" class="user-input_2">
          <igc-radio value="1" class="radio">
            Label
          </igc-radio>
          <igc-radio value="2" class="radio">
            Label
          </igc-radio>
          <igc-radio value="3" class="radio">
            Label
          </igc-radio>
        </igc-radio-group>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Rating
        </p>
        <igc-rating value="${this.value}" size="large" @igcChange="${(e: any) => this.value = e.detail}" class="user-input_2"></igc-rating>
        <igc-rating value="${this.value}" size="large" @igcChange="${(e: any) => this.value = e.detail}" class="user-input_2"></igc-rating>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Select
        </p>
        <igc-select ?outlined="${true}" label="Label/Placeholder" value="${this.value1}" @igcChange="${(e: any) => this.value1 = e.detail.value}" class="user-input">
          ${this.northwindCategories?.map((item) => html`
            <igc-select-item value="${item.categoryID}">
              ${item.name}
            </igc-select-item>
          `)}
        </igc-select>
        <igc-select ?outlined="${true}" label="Label/Placeholder" value="${this.value1}" @igcChange="${(e: any) => this.value1 = e.detail.value}" class="user-input">
          ${this.northwindCategories?.map((item) => html`
            <igc-select-item value="${item.categoryID}">
              ${item.name}
            </igc-select-item>
          `)}
        </igc-select>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Slider
        </p>
        <igc-slider value="${this.value2}" min="0" max="100" step="10" ?discrete-track="${true}" @igcChange="${(e: any) => this.value2 = e.detail}" class="slider"></igc-slider>
        <igc-slider value="${this.value2}" min="0" max="100" step="10" ?discrete-track="${true}" @igcChange="${(e: any) => this.value2 = e.detail}" class="slider"></igc-slider>
        <igc-range-slider .lower="20" .upper="80" .min="0" .max="100" .step="10" .discrete-track="true" class="range-slider"></igc-range-slider>
        <igc-range-slider .lower="20" .upper="80" .min="0" .max="100" .step="10" .discrete-track="true" class="range-slider"></igc-range-slider>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Switch
        </p>
        <igc-switch class="user-input_2">
          Label
        </igc-switch>
        <igc-switch class="user-input_2">
          Label
        </igc-switch>
      </div>
      <div class="column-layout group">
        <p class="typography__body-1 text">
          Calendar
        </p>
        <div class="row-layout group_1">
          <igc-calendar value="${this.value3}" ?hide-header="${false}" header-orientation="horizontal" @igcChange="${(e: any) => this.value3 = e.detail}" class="calendar"></igc-calendar>
          <igc-calendar value="${this.value3}" ?hide-header="${false}" header-orientation="horizontal" @igcChange="${(e: any) => this.value3 = e.detail}" class="calendar"></igc-calendar>
        </div>
      </div>
    `;
  }
}

// angular/src/app/other-inputs/other-inputs.component.ts
import { NgFor } from '@angular/common';
import { Component, OnDestroy, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IgcFormsModule, IGX_CALENDAR_DIRECTIVES, IGX_COMBO_DIRECTIVES, IGX_DATE_PICKER_DIRECTIVES, IGX_INPUT_GROUP_DIRECTIVES, IGX_SELECT_DIRECTIVES, IGX_SIMPLE_COMBO_DIRECTIVES, IGX_SLIDER_DIRECTIVES, IgxCheckboxComponent, IgxRadioComponent, IgxRadioGroupDirective, IgxSwitchComponent } from '@infragistics/igniteui-angular';
import { defineComponents, IgcRatingComponent } from 'igniteui-webcomponents';
import { Subject, takeUntil } from 'rxjs';
import { CategoriesType } from '../models/northwind/categories-type';
import { NorthwindService } from '../services/northwind.service';

defineComponents(IgcRatingComponent);

@Component({
  selector: 'app-other-inputs',
  standalone: true,
  imports: [IGX_SIMPLE_COMBO_DIRECTIVES, IGX_INPUT_GROUP_DIRECTIVES, IGX_DATE_PICKER_DIRECTIVES, IGX_CALENDAR_DIRECTIVES, IGX_SELECT_DIRECTIVES, IGX_SLIDER_DIRECTIVES, IGX_COMBO_DIRECTIVES, IgxRadioGroupDirective, IgxCheckboxComponent, IgxRadioComponent, IgcFormsModule, IgxSwitchComponent, FormsModule, NgFor, FormsModule],
  templateUrl: './other-inputs.component.html',
  styleUrls: ['./other-inputs.component.scss']
})
export class OtherInputsComponent implements OnInit, OnDestroy {
  private destroy$: Subject<void> = new Subject<void>();
  public northwindCategories: CategoriesType[] = [];
  public value: Date = new Date('2024-04-17T00:00');
  public value1: string = '1';
  public value2: number = 3;
  public value3: number = 60;
  public value4: string = '{ lower: 20, upper: 80 }';

  constructor(
    private northwindService: NorthwindService,
  ) {}

  ngOnInit() {
    this.northwindService.getData('CategoriesType').pipe(takeUntil(this.destroy$)).subscribe({
      next: (data) => this.northwindCategories = data,
      error: (_err: any) => this.northwindCategories = []
    });
  }

  ngOnDestroy() {
    this.destroy$.next();
    this.destroy$.complete();
  }
}

<div class="column-layout group">
  <p class="text">
    Check box
  </p>
  <igx-checkbox labelPosition="after" class="user-input_2">
    Label
  </igx-checkbox>
  <igx-checkbox labelPosition="after" class="user-input_2">
    Label
  </igx-checkbox>
</div>
<div class="column-layout group">
  <p class="text">
    Combo
  </p>
  <igx-simple-combo type="border" [data]="northwindCategories" valueKey="categoryID" displayKey="description" class="user-input">
    <label igxLabel>Single select</label>
  </igx-simple-combo>
  <igx-simple-combo type="border" [data]="northwindCategories" valueKey="categoryID" displayKey="description" class="user-input">
    <label igxLabel>Single select</label>
  </igx-simple-combo>
  <igx-combo type="border" [data]="northwindCategories" valueKey="categoryID" displayKey="description" [autoFocusSearch]="true" class="user-input">
    <label igxLabel>Multi select</label>
  </igx-combo>
  <igx-combo type="border" [data]="northwindCategories" valueKey="categoryID" displayKey="description" [autoFocusSearch]="true" class="user-input">
    <label igxLabel>Multi select</label>
  </igx-combo>
</div>
<div class="column-layout group">
  <p class="text">
    Date picker
  </p>
  <igx-date-picker [(ngModel)]="value" type="border" mode="dialog" class="date-picker">
    <label igxLabel>Date</label>
  </igx-date-picker>
  <igx-date-picker [(ngModel)]="value" type="border" mode="dialog" class="date-picker">
    <label igxLabel>Date</label>
  </igx-date-picker>
</div>
<div class="column-layout group">
  <p class="text">
    Radio group
  </p>
  <igx-radio-group [(ngModel)]="value1" class="user-input_2">
    <igx-radio value="1" class="radio">
      Label
    </igx-radio>
    <igx-radio value="2" class="radio">
      Label
    </igx-radio>
    <igx-radio value="3" class="radio">
      Label
    </igx-radio>
  </igx-radio-group>
  <igx-radio-group [(ngModel)]="value1" class="user-input_2">
    <igx-radio value="1" class="radio">
      Label
    </igx-radio>
    <igx-radio value="2" class="radio">
      Label
    </igx-radio>
    <igx-radio value="3" class="radio">
      Label
    </igx-radio>
  </igx-radio-group>
</div>
<div class="column-layout group">
  <p class="text">
    Rating
  </p>
  <igc-rating [(ngModel)]="value2" size="large" class="user-input_2"></igc-rating>
  <igc-rating [(ngModel)]="value2" size="large" class="user-input_2"></igc-rating>
</div>
<div class="column-layout group">
  <p class="text">
    Select
  </p>
  <igx-select type="border" [(ngModel)]="value1" class="user-input">
    <igx-select-item [value]="item.categoryID" *ngFor="let item of northwindCategories">
      {{ item.name }}
    </igx-select-item>
    <label igxLabel>Label/Placeholder</label>
  </igx-select>
  <igx-select type="border" [(ngModel)]="value1" class="user-input">
    <igx-select-item [value]="item.categoryID" *ngFor="let item of northwindCategories">
      {{ item.name }}
    </igx-select-item>
    <label igxLabel>Label/Placeholder</label>
  </igx-select>
</div>
<div class="column-layout group">
  <p class="text">
    Slider
  </p>
  <igx-slider [(ngModel)]="value3" [minValue]="0" [maxValue]="100" [step]="10" [secondaryTickLabels]="false" class="slider"></igx-slider>
  <igx-slider [(ngModel)]="value3" [minValue]="0" [maxValue]="100" [step]="10" [secondaryTickLabels]="false" class="slider"></igx-slider>
  <igx-slider type="range" [(ngModel)]="value4" [minValue]="0" [maxValue]="100" [step]="10" [secondaryTickLabels]="false" class="slider"></igx-slider>
  <igx-slider type="range" [(ngModel)]="value4" [minValue]="0" [maxValue]="100" [step]="10" [secondaryTickLabels]="false" class="slider"></igx-slider>
</div>
<div class="column-layout group">
  <p class="text">
    Switch
  </p>
  <igx-switch class="user-input_2">
    Label
  </igx-switch>
  <igx-switch class="user-input_2">
    Label
  </igx-switch>
</div>
<div class="column-layout group">
  <p class="text">
    Calendar
  </p>
  <div class="row-layout group_1">
    <igx-calendar [(ngModel)]="value" [hasHeader]="true" [vertical]="false" class="calendar"></igx-calendar>
    <igx-calendar [(ngModel)]="value" [hasHeader]="true" [vertical]="false" class="calendar"></igx-calendar>
  </div>
</div>
