// react/src/app/input-group/input-group.tsx
import { IgrDateTimeInput, IgrDateTimeInputModule, IgrInput, IgrInputModule } from '@infragistics/igniteui-react';
import createClassTransformer from '../style-utils';
import styles from './input-group.module.css';

IgrDateTimeInputModule.register();
IgrInputModule.register();

export default function InputGroup() {
  const classes = createClassTransformer(styles);

  return (
    <>
      <div className={classes("row-layout input-group-container")}>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Text</p>
          <IgrInput value="Text" label="Text" className={classes("input")}></IgrInput>
        </div>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Numeric</p>
          <IgrInput type="number" value="500" label="Numeric" className={classes("input")}></IgrInput>
        </div>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Email</p>
          <IgrInput type="email" value="test@test.dev" label="Email" className={classes("input")}></IgrInput>
        </div>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Password</p>
          <IgrInput type="password" value="Password" label="Password" className={classes("input")}></IgrInput>
        </div>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Phone</p>
          <IgrInput type="tel" value="Phone" label="Phone" className={classes("input")}></IgrInput>
        </div>
        <div className={classes("column-layout group")}>
          <p className={classes("typography__body-1 text")}>Type Date</p>
          <IgrDateTimeInput label="Date" className={classes("date-time-input")}></IgrDateTimeInput>
        </div>
      </div>
    </>
  );
}

// angular/src/app/input-group/input-group.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { IGX_INPUT_GROUP_DIRECTIVES, IgxDateTimeEditorModule } from '@infragistics/igniteui-angular';

@Component({
  selector: 'app-input-group',
  standalone: true,
  imports: [IGX_INPUT_GROUP_DIRECTIVES, IgxDateTimeEditorModule, FormsModule],
  templateUrl: './input-group.component.html',
  styleUrls: ['./input-group.component.scss']
})
export class InputGroupComponent {
  public value: string = 'Text';
  public value1: number = 500;
  public value2: string = 'test@test.dev';
  public value3: string = 'Password';
  public value4: string = 'Phone';
  public date: Date = new Date('2010-10-10T00:00');
}

<div class="column-layout group">
  <p class="text">
    Type Text
  </p>
  <igx-input-group type="border" class="user-input">
    <input type="text" [(ngModel)]="value" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Text</label>
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <input type="text" [(ngModel)]="value" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Text</label>
  </igx-input-group>
</div>
<div class="column-layout group">
  <p class="text">
    Type Numeric
  </p>
  <igx-input-group type="border" class="user-input">
    <input type="number" [(ngModel)]="value1" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Numeric</label>
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <input type="number" [(ngModel)]="value1" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Numeric</label>
  </igx-input-group>
</div>
<div class="column-layout group">
  <p class="text">
    Type Email
  </p>
  <igx-input-group type="border" class="user-input">
    <input type="email" [(ngModel)]="value2" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Email</label>
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <input type="email" [(ngModel)]="value2" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Email</label>
  </igx-input-group>
</div>
<div class="column-layout group">
  <p class="text">
    Type Password
  </p>
  <igx-input-group type="border" class="user-input">
    <input type="password" [(ngModel)]="value3" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Password</label>
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <input type="password" [(ngModel)]="value3" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Password</label>
  </igx-input-group>
</div>
<div class="column-layout group">
  <p class="text">
    Type Phone
  </p>
  <igx-input-group type="border" class="user-input">
    <input type="tel" [(ngModel)]="value4" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Phone</label>
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <input type="tel" [(ngModel)]="value4" igxInput [ngModelOptions]="{updateOn: 'blur'}" />
    <label igxLabel>Phone</label>
  </igx-input-group>
</div>
<div class="column-layout group">
  <p class="text">
    Type Date
  </p>
  <igx-input-group type="border" class="user-input">
    <label igxLabel for="inputField">Date</label>
    <input name="inputField" [required]="false" [disabled]="false" igxInput igxDateTimeEditor="yyyy/MM/dd" displayFormat="shortDate" [spinLoop]="true" [(ngModel)]="date" />
  </igx-input-group>
  <igx-input-group type="border" class="user-input">
    <label igxLabel for="inputField">Date</label>
    <input name="inputField" [required]="false" [disabled]="false" igxInput igxDateTimeEditor="yyyy/MM/dd" displayFormat="shortDate" [spinLoop]="true" [(ngModel)]="date" />
  </igx-input-group>
</div>
